defaults: &defaults
  credentials:
    github:
      token: CLIENT_ID
      secret: CLIENT_SECRET

development:
  <<: *defaults

production:
  <<: *defaults

test:
  credentials:
    github:
      token: NIL
      secret: NIL
